language: scala
scala:
  - 2.13.1
deploy:
  provider: pages
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master